image: hub.nstda.or.th/bt/docker:ci.stable

stages:
  - init
  - test
  - deploy

init:
  stage: init
  script:
    - if [ "$CI_COMMIT_TAG" != "pro" ] && [ "$CI_COMMIT_TAG" != "test" ] && ! [[ "$CI_COMMIT_TAG" =~ ^test=[a-z0-9,_]{1,250}$ ]]; then echo "TAG ERROR!!" && exit 1; fi
  only:
    - tags
  tags: 
    - o.nstda/init

test-install:
  stage: test
  services:
    - name: hub.nstda.or.th/bt/docker:dind.stable
      alias: docker
  coverage: '/TOTAL.*\s+(\d+%)$/'
  script:
    - git clone https://$MCI_USER:$MCI_PASSWORD@git.nstda.or.th/`echo "$CI_PROJECT_NAMESPACE" | cut -d'/' -f1`/gitlab-ci.git $CI_PROJECT_DIR/tmp/gitlab-ci
    - bash $CI_PROJECT_DIR/tmp/gitlab-ci/ti.sh "$CI_PROJECT_DIR/tmp/gitlab-ci"
  only:
    - tags
  tags:
    - o.nstda/test

deploy:
  stage: deploy
  services:
    - name: hub.nstda.or.th/bt/docker:dind.stable
      alias: docker
  script:
    - git clone https://$MCI_USER:$MCI_PASSWORD@git.nstda.or.th/`echo "$CI_PROJECT_NAMESPACE" | cut -d'/' -f1`/gitlab-ci.git $CI_PROJECT_DIR/tmp/gitlab-ci
    - bash $CI_PROJECT_DIR/tmp/gitlab-ci/run.sh "$CI_PROJECT_DIR/tmp/gitlab-ci"
  only:
    - tags
  tags:
    - o.nstda/deploy
