image: hub.nstda.or.th/bt/docker:ci.stable
services: 
  - hub.nstda.or.th/bt/docker:dind.stable

stages:
  - init
  - test
  - deploy

init:
  stage: init
  script:
    - if [ "$CI_COMMIT_TAG" != "pro" ] && [ "$CI_COMMIT_TAG" != "test" ]; then echo "TAG ERROR!!" && exit 1; fi
  only:
    - tags
  tags: 
    - o.nstda/init

####################################################################################
##### avariable to write the gitlab-ci for test your sourcecode in this table. #####
####################################################################################
#
#test-[SCENARIO]:
#  stage: test
#  script:
#    - [..........]
#    - [..........]
#    - [..........]
#  only:
#    - tags
#  tags:
#    - o.nstda/test
#
####################################################################################
####################################################################################

test-install:
  stage: test
  script:
    - git clone https://$MCI_USER:$MCI_PASSWORD@git.nstda.or.th/`echo "$CI_PROJECT_NAMESPACE" | cut -d'/' -f1`/gitlab-ci.git $CI_PROJECT_DIR/tmp/gitlab-ci
    - bash $CI_PROJECT_DIR/tmp/gitlab-ci/ti.sh "$CI_PROJECT_DIR/tmp/gitlab-ci"
  only:
    - tags
  tags:
    - o.nstda/test

deploy:
  stage: deploy
  script:
    - git clone https://$MCI_USER:$MCI_PASSWORD@git.nstda.or.th/`echo "$CI_PROJECT_NAMESPACE" | cut -d'/' -f1`/gitlab-ci.git $CI_PROJECT_DIR/tmp/gitlab-ci
    - bash $CI_PROJECT_DIR/tmp/gitlab-ci/run.sh "$CI_PROJECT_DIR/tmp/gitlab-ci"
  only:
    - tags
  tags:
    - o.nstda/deploy